### ISSUE TITLE
Support `cp something ~/.bin`

### ISSUE THREAD

**Issue by certik** [prefix-dev/shell#44]
```
~/repos/shell$ cp target/release/shell.exe ~/bin
cp: could not copy target/release/shell.exe to ~/bin: The system cannot find the path specified. (os error 3)
```

The `~/bin` does not work.

**Comment by certik** [comment]
Same with `ls` and also launching programs using `~/bin/shell.exe`

**Comment by wolfv** [comment]
I think this relates to the idea of pre-processing the `~` string and expanding it to `$HOME`.

**Comment by certik** [comment]
Note that there is no `$HOME` on Windows, but `shell` already knows how to get it via deno's `dirs::home_dir()`, which is a package.

**Comment by certik** [comment]
This now works, it was fixed in https://github.com/prefix-dev/shell/pull/85.
