### ISSUE TITLE
implement `which`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/shell#63]
I think we should implement which. It's pretty annoying to not have it on Windows. 

However, `which` also shows if a tool is an alias or bash function. We would have to figure out how to do that. 

We can use the `which` crate though: https://docs.rs/which/latest/which/

**Comment by certik** [comment]
Works like a charm:
```
~$ which shell
C:\Users\ondrejcertik\bin\shell.exe
~$ which git
C:\Program Files\Git\cmd\git.exe
~$ which vi
C:\Users\ondrejcertik\bin\vi.bat
~$ which vim
C:\Users\ondrejcertik\.pixi\bin\vim.bat
~$ which ssh
C:\Windows\System32\OpenSSH\ssh.exe
~$ which ls
<builtin function>
```
