### ISSUE TITLE
Switch to miette for error handling for pest

### ISSUE THREAD

**Issue by certik** [prefix-dev/shell#77]
See https://github.com/prefix-dev/shell/issues/33#issuecomment-2334443728.

**Comment by prsabahrami** [comment]
Just merged the PR on miette support for pest! https://github.com/pest-parser/pest/pull/1038
I will start working on this!

**Comment by Hofer-Julian** [comment]
> Just merged the PR on miette support for pest! [pest-parser/pest#1038](https://github.com/pest-parser/pest/pull/1038) I will start working on this!

Awesome 🥳
Let's make sure to get rid of anyhow completely then

**Comment by certik** [comment]
Fixed in https://github.com/prefix-dev/shell/pull/117.
