### ISSUE TITLE
Interactive mode exiting on unsupported complex commands

### ISSUE THREAD

**Issue by prsabahrami** [prefix-dev/shell#86]
I don't think this should happen upon unsuppoted features.
<img width="633" alt="image" src="https://github.com/user-attachments/assets/35395652-364f-49b2-8427-c851f7b4cd5b">

Instead of using `todo!()`, I think it is preferrably better to throw an error and continue in the interactive mode.

**Comment by certik** [comment]
Yes, this is similar to https://github.com/prefix-dev/shell/issues/33.
